### ISSUE TITLE
dosent work - fully black screen

### ISSUE THREAD

**Issue by mutageneral** [Spydr06/xcorners#1]
When I run `./xcorners` all my screens turn fully black and the program says `unhandled event: 65` in the terminal.

**Comment by Spydr06** [comment]
You need a compositor to get it to work. Sry I didn't specify it in the readme

**Comment by Spydr06** [comment]
I added a note in the README in debaacd, closing this for now.
If you still have issues, please open another issue.

**Comment by mutageneral** [comment]
with the compositor on, all my screen become blurry
I added rule for xconrers:
```
  "class_g = 'xcorners'",
```

but there is only one black corner in the top left of my monitor on the left
dose the program support showing the 4 corners on each screens?

**Comment by Spydr06** [comment]
Yes it does using the `-b` flag, look at the `--help` output. 

If you have more than one monitor, you'll have to set the offset and size yourself.
If you want corners on each monitor, just use multiple instances.
